---
name: Update CLI reference

on:
  schedule:
    - cron: '0 6 * * *' # runs daily at 6
  workflow_dispatch:

jobs:
  generate:
    name: Generate CLI reference
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Generate CLI reference
        run: scripts/src/generate-cli-reference.lua
      - uses: peter-evans/create-pull-request@v7
        with:
          add-paths: docs/reference/cli.md
          commit-message: "docs: update CLI reference"
          title: "docs: update CLI reference"
          body: |
            Automated update of the CLI reference from the latest man page.
          branch: update-cli-reference
          delete-branch: true
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
